# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ksarch-Store
tagline:          'Tech Blog'
description:      'A storage team at Baidu,Inc. lol'
url:              http://ksarch-store.github.io
baseurl:          /
paginate:         5

author:
  name:           'Ksarch-Store'
  url:            https://twitter.com/ksarch-store

# Custom vars
# version:          1.0.0

github:
  repo:           https://github.com/ksarch-store
