# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Ksarch-SaaS
tagline:          'Tech Blog'
description:      'A storage team at Baidu,Inc. lol'
url:              http://ksarch-saas.github.io
baseurl:          /
paginate:         5

author:
  name:           'Ksarch-SaaS'
  url:            https://twitter.com/ksarch-saas

# Custom vars
# version:          1.0.0

github:
  repo:           https://github.com/ksarch-saas
