# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ksarch-Store
tagline:          'Tech Blog'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://ksarch-store.github.io
paginate:         5

author:
  name:           'Ksarch-Store'
  url:            https://twitter.com/ksarch-store

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
